spring:
  datasource:
     url: jdbc:mysql://localhost:3306/apilocal?useUnicode=true&characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver

thrift:
  port: 7911
  minWorkerThreads: 1
  maxWorkerThreads: 3